# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'del_division.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QWidget, QMessageBox

from request_base import Request


class DelDivision(QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("del_division")
        self.setWindowTitle("Видалення розділу витрат")
        self.setFixedSize(400, 240)
        self.request = Request()

        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(30, 180, 340, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(50, 30, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setText("Оберіть назву розділу для видалення")

        self.verticalLayoutWidget = QtWidgets.QWidget(self)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 80, 260, 50))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.label_2.setText("Скорочена назва непотрібного розхділу")
        self.verticalLayout.addWidget(self.label_2)

        self.short_name_div = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.short_name_div.setObjectName("lineEdit")
        self.short_name_div.setPlaceholderText("Скороченне ім\'я розділу")
        self.verticalLayout.addWidget(self.short_name_div)

        self.buttonBox.accepted.connect(self.accept_click)
        self.buttonBox.rejected.connect(self.close)

    @pyqtSlot()
    def accept_click(self):
        short_name = self.short_name_div.text()
        if short_name != '':
            self.sql_req = "DELETE FROM system WHERE div = '" + short_name + "';"
            self.request.execute_data(self.sql_req)
            QMessageBox.information(self, "Вітаю!", "Розділ було успішно видаленно!", QMessageBox.Ok, QMessageBox.Ok)
            self.close()
        else:
            QMessageBox.critical(self, "Відсутнє скороченне ім'я розділу!",
                                 "Введіть скорочену назву розділу для видалення!", QMessageBox.Ok, QMessageBox.Ok)



