# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from window_add_profit import *
from window_regular_payments import *
from window_statistic import *
from window_unregular_payments import *


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.current_payments = RegularPaymentWindow()
        self.statistic = StatisticWindow()
        self.unregular_payments = UnregularPayments(self.statistic)
        self.add_profit = AddProfitWindow(self.statistic)

        self.setObjectName("MainWindow")
        self.setEnabled(True)
        self.setFixedSize(MAIN_WINDOW_LENGTH, MAIN_WINDOW_HEIGHT)
        self.setWindowTitle("Приватний бухгалтерський облік")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        """ 0, 30, 800, 60 Ласкаво просимо до Вашого фінансового помічника !!! 14 """
        self._write_label_welcome(0, 30, 800, 60, "Ласкаво просимо до Вашого фінансового помічника !!!", 14, True)

        """ Welcoming speach """
        self._write_label_welcome(10, 115, 780, 90,
                                  "Програма допоможе Вам вести ваші фінансові справи значно ефективніше ніж "
                                  "раніше.\n Ви зможете зрозуміліше контролювати Ваші витрати.\n Також Ви зможете "
                                  "прогнузувати Ваші витрати на майбутнє.\n"
                                  " Насолоджуйтеся!", 11)

        """ Button Exit """
        self.button_close = QtWidgets.QPushButton(self.centralwidget)
        self.button_close.setGeometry(QtCore.QRect(595, 465, 150, 50))
        self.button_close.setObjectName("closebutton")
        self.button_close.setText("Вихід з програми")
        self.button_close.clicked.connect(self.push_button_exit)
        """ Layout with buttons and labels"""
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 230, 240, 210))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        """ Button current payments """
        self.button_current_payments = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_current_payments.setMaximumSize(QtCore.QSize(16777215, 30))
        self.button_current_payments.setObjectName("button_current_payments")
        self.button_current_payments.setText("Поточні витрати")
        self.verticalLayout.addWidget(self.button_current_payments)
        self.button_current_payments.clicked.connect(self.push_current_payments)

        self.pushButton_statistic = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_statistic.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_statistic.setObjectName("pushButton_statistic")
        self.pushButton_statistic.setText("Статистика")
        self.verticalLayout.addWidget(self.pushButton_statistic)
        self.pushButton_statistic.clicked.connect(self.push_statistic)

        self.button_unreg_payments = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_unreg_payments.setMaximumSize(QtCore.QSize(16777215, 30))
        self.button_unreg_payments.setObjectName("button_unreg_payments")
        self.button_unreg_payments.setText("Внести нерегулярні платежі")
        self.verticalLayout.addWidget(self.button_unreg_payments)
        self.button_unreg_payments.clicked.connect(self.push_payments)

        self.button_profit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_profit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.button_profit.setObjectName("button_profit")
        self.button_profit.setText("Надходження")
        self.verticalLayout.addWidget(self.button_profit)
        self.button_profit.clicked.connect(self.get_profit)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(330, 230, 440, 210))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName("label_3")
        self.label_3.setText("   - перехід до Ваших фінансових справ")
        self.verticalLayout_2.addWidget(self.label_3)

        self.label_stat = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_stat.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_stat.setObjectName("label_stat")
        self.label_stat.setText("   - статистика Ваших витрат")
        self.verticalLayout_2.addWidget(self.label_stat)

        self.label_payments = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_payments.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_payments.setObjectName("label_payments")
        self.label_payments.setText("  - різні не регулярні витрати")
        self.verticalLayout_2.addWidget(self.label_payments)

        self.label_get_profit = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_get_profit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_get_profit.setObjectName("label_get_profit")
        self.label_get_profit.setText("  - Ваші надходження")
        self.verticalLayout_2.addWidget(self.label_get_profit)

        self.setCentralWidget(self.centralwidget)

    def push_current_payments(self):
        self.current_payments.show()

    def push_statistic(self):
        self.statistic.show()

    def push_payments(self):
        self.unregular_payments.show()

    def get_profit(self):
        self.add_profit.show()

    @staticmethod
    def push_button_exit():
        exit()

    def _write_label_welcome(self, x1, y1, x2, y2, text, font_size, bolt=False):
        label_welcome = QtWidgets.QLabel(self.centralwidget)
        label_welcome.setGeometry(QtCore.QRect(x1, y1, x2, y2))
        font = QtGui.QFont()
        font.setPointSize(font_size)
        font.setBold(bolt)
        label_welcome.setFont(font)
        label_welcome.setTabletTracking(False)
        label_welcome.setLayoutDirection(QtCore.Qt.LeftToRight)
        label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        label_welcome.setWordWrap(True)
        label_welcome.setText(text)

    def keyPressEvent(self, e):
        if e.key() == Qt.Key_Escape:
            self.close()
