# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_division.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot, Qt
from PyQt5.QtWidgets import QMessageBox, QCheckBox, QDialog, QDialogButtonBox

from request_base import Request


class WindowNewCustomer(QDialog):
    def __init__(self, parent=None, tab_widget=None):
        super().__init__(parent)
        self.div = tab_widget
        self.setObjectName("new_customer")
        self.setWindowTitle("Новий постачальник послуг")
        self.setFixedSize(400, 290)

        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(30, 180, 340, 150))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.addButton("Додати", QDialogButtonBox.AcceptRole)
        self.buttonBox.addButton("Відміна", QDialogButtonBox.RejectRole)
        self.buttonBox.setObjectName("buttonBox")

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(50, 30, 290, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setText(f"Введіть назву нових посуг \nдо розділу: '{self.div}'")

        self.verticalLayoutWidget = QtWidgets.QWidget(self)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 100, 260, 110))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # self.div_for_new_customer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        # self.div_for_new_customer.setObjectName("div_for_new_customer")
        # self.div_for_new_customer.setPlaceholderText("Им\'я розділу для додавання постачальника")
        # self.div_for_new_customer.setMaxLength(15)
        # self.div_for_new_customer.setFixedWidth(150)
        # self.verticalLayout.addWidget(self.div_for_new_customer)

        self.new_customer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.new_customer.setObjectName("new_customer")
        self.new_customer.setPlaceholderText("Им\'я нового постачальника послуг")
        self.new_customer.setMaxLength(15)
        self.verticalLayout.addWidget(self.new_customer)

        self.base_price = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.base_price.setObjectName("base_price")
        self.base_price.setPlaceholderText("Ціна послуг за одиницю")
        self.base_price.setFixedWidth(150)
        self.verticalLayout.addWidget(self.base_price)

        """ Checkbox for add counter """
        self.counter_checkbox = QCheckBox("Додати до розрахунку поля лічильника", self)
        self.verticalLayout.addWidget(self.counter_checkbox)
        self.counter_checkbox.stateChanged.connect(self.add_qline_by_checkbox)

        """ First state of counter """
        self.qline_start_counter = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.qline_start_counter.setObjectName("qline_start_counter")
        self.qline_start_counter.setFixedWidth(150)
        self.qline_start_counter.setEnabled(False)
        self.verticalLayout.addWidget(self.qline_start_counter)

        """Button for close/accept"""
        self.buttonBox.accepted.connect(self.__accept_click)
        self.buttonBox.rejected.connect(self.close)

    def add_qline_by_checkbox(self):
        if self.counter_checkbox.isChecked():
            self.qline_start_counter.setEnabled(True)
            self.qline_start_counter.setPlaceholderText("Перші показники лічильника")
        else:
            self.qline_start_counter.setEnabled(False)
            self.qline_start_counter.setPlaceholderText("")

    @pyqtSlot()
    def __accept_click(self):
        __div = self.div
        __new_customer = self.new_customer.text()
        __base_price = self.base_price.text()
        __counter = self.qline_start_counter.text()

        request = Request()
        req_select_div = "SELECT div, name_customer FROM system"
        data = request.show_base(req_select_div)
        print(data)

        if (__div, __new_customer) in data:
            QMessageBox.critical(self, "Увага!",
                                 f"Постачальник {__new_customer} вже існує!\n"
                                 f"Введіть унікальне ім'я постачальника послуг!\n"
                                 , QMessageBox.Ok, QMessageBox.Ok)
            self.new_customer.setText('')
        elif __new_customer == '':
            QMessageBox.critical(self, "Увага!",
                                 "Відсутнє ім'я постачальника!\n"
                                 "Введіть ім'я постачальника послуг!",
                                 QMessageBox.Ok, QMessageBox.Ok)
        elif __base_price == '':
            QMessageBox.critical(self, "Увага!",
                                 "Відсутнє базова ціна послуг,\n"
                                 "або некоректна базова ціна послуг!\n\n"
                                 "Введіть ціну послуг за одиницю!\n",
                                 QMessageBox.Ok, QMessageBox.Ok)

        else:
            if self.counter_checkbox.isChecked():
                sql_req = "INSERT INTO system (div, name_customer, first_price, first_counter) " \
                          "VALUES ('" + __div + "', '" + __new_customer + "', '" + __base_price + "', '" + __counter + "')"
            else:
                sql_req = "INSERT INTO system (div, name_customer, first_price) " \
                          "VALUES ('" + __div + "', '" + __new_customer + "', '" + __base_price + "')"
            request = Request()
            request.execute_data(sql_req)
            QMessageBox.information(self, "Вітаю!", "Успішно додано нового постачальника!", QMessageBox.Ok, QMessageBox.Ok)
            self.close()


