# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'some_else.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot, Qt
from PyQt5.QtWidgets import QLineEdit, QMessageBox, QWidget
from request_base import Request


class AddProfitWindow(QWidget):
    def __init__(self, stat_window=None):
        super().__init__()
        self.stat_window = stat_window
        self.setObjectName("AddProfitWindow")
        self.setWindowTitle("Надходження")
        self.setFixedSize(420, 240)

        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(30, 180, 340, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(38, 20, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setText("Надходження до Вашого бюджету:")

        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 330, 40))
        self.gridLayoutWidget.setObjectName("gridLayout_tab")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.label_2.setText(" Опис надходженя грошей:")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.label_3.setText(" Cума до зарахування:")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)

        self.coast = QLineEdit(self)
        self.coast.setObjectName("coast")
        self.coast.setPlaceholderText("Сума, грн..")
        self.gridLayout.addWidget(self.coast, 1, 1, 1, 1)

        self.name_profit = QLineEdit(self)
        self.name_profit.setObjectName("name_profit")
        self.name_profit.setPlaceholderText("Походження надходжень")
        self.gridLayout.addWidget(self.name_profit, 1, 0, 1, 1)

        self.buttonBox.accepted.connect(self.push_profit)
        self.buttonBox.rejected.connect(self.close)

    @pyqtSlot()
    def push_profit(self):
        textbox_value = self.name_profit.text()
        if textbox_value != '':
            try:
                coast = float(self.coast.text())
                coast = abs(coast)
                text_message = textbox_value + ": " + str(coast) + "грн."
                QMessageBox.information(self, 'Успішний запис надходжень!', text_message, QMessageBox.Ok, QMessageBox.Ok)
                request = Request()
                sql_req = "INSERT INTO payments (name_pay, money, date) VALUES ('" + textbox_value + "', " + str(
                    coast) + ", datetime('now', 'localtime'))"
                request.execute_data(sql_req)
                self.name_profit.setText("")
                if self.stat_window is not None:
                    self.stat_window.button_refresh()
            except ValueError:
                QMessageBox.critical(self, 'Некоректна сума!',
                                     'Спробуйте ще раз ввести суму..', QMessageBox.Ok, QMessageBox.Ok)
        else:
            QMessageBox.critical(self, 'Відсутнє походження суми грошей!',
                                 'Спробуйте ще раз ввести походження суми до зарахування..', QMessageBox.Ok, QMessageBox.Ok)
        self.coast.setText("")

    def keyPressEvent(self, e):
        if e.key() == Qt.Key_Escape:
            self.close()


