# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'СurrentСosts.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import main_window

from new_division import NewDivision
from del_division import DelDivision
from request_base import Request


class CurrentCosts(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.tab = None
        self.setObjectName("CurrentCosts")
        self.setWindowTitle("Щомісячні витрати")
        self.resize(850, 530)

        self.sql_req = "SELECT * FROM system"
        self.request = Request()
        self.data = self.request.show_base(self.sql_req)
        """main layout"""
        self.verticalLayoutWidget = QtWidgets.QWidget(self)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(650, 340, 180, 170))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.layout_main_button()
        self.tab_widget()
        self.group_box()

    def layout_main_button(self):
        """main buttons"""
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        """new division"""
        self.newdivision = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.newdivision.setObjectName("newdivision")
        self.verticalLayout.addWidget(self.newdivision)
        self.newdivision.setText("Створити новий розділ витрат")
        self.newdivision.clicked.connect(self.new_division)
        """delete division"""
        self.del_div_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.del_div_button.setObjectName("del_div_button")
        self.verticalLayout.addWidget(self.del_div_button)
        self.del_div_button.setText("Видалити розділ")
        self.del_div_button.clicked.connect(self.del_division)

        """close window"""
        self.closebutton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.closebutton.setObjectName("closebutton")
        self.verticalLayout.addWidget(self.closebutton)
        self.closebutton.setText("Закрити вікно")
        self.closebutton.clicked.connect(self.close)
        """exit program"""
        self.close_program_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.close_program_button.setObjectName("close_program_button")
        self.verticalLayout.addWidget(self.close_program_button)
        self.close_program_button.setText("Вихід з програми")
        self.close_program_button.clicked.connect(main_window.MainWindow.push_button_exit)

    def tab_widget(self):
        """Tab widget - division"""
        self.tabWidget = QtWidgets.QTabWidget(self)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 610, 500))
        self.tabWidget.setObjectName("tabWidget")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 410, 100, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setText("Оновити")

        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(479, 410, 100, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setText("Внести зміни")

        self.dateEdit = QtWidgets.QDateEdit(self.tab)  # calendar
        self.dateEdit.setGeometry(QtCore.QRect(50, 410, 90, 30))
        self.dateEdit.setObjectName("dateEdit")

    def group_box(self):
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 30, 540, 360))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_2.setTitle("Розрахунок поточних платежів:")

        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 520, 300))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox.setText("Вода та стоки")

        self.lineEdit_price = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.gridLayout.addWidget(self.lineEdit_price, 0, 1, 1, 1)

        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 2, 1, 1)  # temporary label

        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_7.setPlaceholderText("Кількість")
        self.gridLayout.addWidget(self.lineEdit_8, 0, 3, 1, 1)

        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 0, 4, 1, 1)

        index_finish = 10
        index_start = 0
        while index_start != index_finish:

            self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
            self.label_9.setAlignment(QtCore.Qt.AlignCenter)
            self.label_9.setObjectName("label_9")
            self.label_9.setText("Сплаченно")
            self.gridLayout.addWidget(self.label_9, index_start, 5, 1, 1)

            self.label_100 = QtWidgets.QLabel(self.gridLayoutWidget)
            self.label_100.setAlignment(QtCore.Qt.AlignCenter)
            self.label_100.setObjectName("label_100")
            self.label_100.setText(" ")
            self.gridLayout.addWidget(self.label_100, index_start + 1, 5, 1, 1)
            index_start += 2

        self.spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(self.spacerItem, 100, 1, 1, 1)
        """  -------------   """

        """   -------------   """
        """   Line into tab   """
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(10, 40, 520, 15))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(110, 20, 100, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_12.setText("Ціна, грн")

        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(210, 20, 80, 20))
        self.label_14.setAutoFillBackground(False)
        self.label_14.setScaledContents(False)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_14.setText("Показники ліч")

        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(300, 20, 80, 20))
        self.label_16.setAutoFillBackground(False)
        self.label_16.setScaledContents(False)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_16.setText("Показники ліч")

        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(390, 20, 80, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_17.setText("До сплати, грн")

        self.tabWidget.addTab(self.tab, "")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), ("122"))

        for id_div in self.data:
            print(id_div[0])
            self.tab = QtWidgets.QWidget()
            self.tab.setObjectName(f"{id_div[0]}")


            self.pushButton = QtWidgets.QPushButton(self.tab)
            self.pushButton.setGeometry(QtCore.QRect(370, 410, 100, 30))
            self.pushButton.setObjectName(f"{id_div[2]}")
            self.pushButton.setText(f"{id_div[2]}")

            self.tabWidget.addTab(self.tab, "")
            self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), f"{id_div[1]}")


        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(660, 40, 160, 40))
        self.label.setObjectName("label")

        """   Line   """
        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(650, 70, 180, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        """  Line under main buttons"""
        self.line_3 = QtWidgets.QFrame(self)
        self.line_3.setGeometry(QtCore.QRect(650, 320, 180, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        """  Line   """
        self.line_4 = QtWidgets.QFrame(self)
        self.line_4.setGeometry(QtCore.QRect(20, 500, 810, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(650, 90, 180, 130))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)

        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)

        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(650, 240, 180, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)

        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)

        self.line_5 = QtWidgets.QFrame(self)
        self.line_5.setGeometry(QtCore.QRect(650, 220, 180, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.retranslateUi(self)
        # self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, CurrentCosts):
        _translate = QtCore.QCoreApplication.translate
        # self.checkBox_8.setText(_translate("CurrentCosts", "Vodafon"))
        # self.checkBox_6.setText(_translate("CurrentCosts", "Розподіл газу"))
        #
        # self.checkBox_4.setText(_translate("CurrentCosts", "Електроенергія"))
        # self.checkBox_3.setText(_translate("CurrentCosts", "Вода"))
        # self.label_19.setText(_translate("CurrentCosts", "TextLabel"))
        # self.label_18.setText(_translate("CurrentCosts", "TextLabel"))
        # self.checkBox_2.setText(_translate("CurrentCosts", "Охорона"))
        # self.checkBox_5.setText(_translate("CurrentCosts", "Газ"))
        #
        # self.label_10.setText(_translate("CurrentCosts", "Відсутній"))
        # self.label_13.setText(_translate("CurrentCosts", "TextLabel"))
        # self.checkBox_7.setText(_translate("CurrentCosts", "Інтернет"))
        # self.label_11.setText(_translate("CurrentCosts", "TextLabel"))
        # self.label_15.setText(_translate("CurrentCosts", "TextLabel"))
        # self.label_20.setText(_translate("CurrentCosts", "TextLabel"))
        # self.label_8.setText(_translate("CurrentCosts", "Постачальник"))


        self.label.setText(_translate("CurrentCosts", "Обов\'язкові поточні платежи"))
        self.label_2.setText(_translate("CurrentCosts", "Вода"))
        self.label_4.setText(_translate("CurrentCosts", "Інтернет"))
        self.label_3.setText(_translate("CurrentCosts", "Охорона"))
        self.label_5.setText(_translate("CurrentCosts", "TextLabel"))
        self.label_6.setText(_translate("CurrentCosts", "Орієнтовна сума до сплати: 2000грн"))

    def new_division(self):
        self.dialog_NewDivision = NewDivision()
        self.dialog_NewDivision.show()

    def del_division(self):
        self.dialog_DelDivision = DelDivision()
        self.dialog_DelDivision.show()

